version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DEMO_MODE=true
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: python -m src.main
    depends_on:
      - redis
      - qdrant

  # Streamlit Frontend  
  frontend:
    build: .
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000/api/v1
    volumes:
      - ./src/frontend:/app/src/frontend
    command: streamlit run src/frontend/app.py --server.address 0.0.0.0 --server.port 8501
    depends_on:
      - backend

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Vector Database (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  redis_data:
  qdrant_data:

networks:
  default:
    name: rare-drug-ai