version: '3.8'

services:
  medai-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    env_file:
      - config/.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/static:/var/www/static
    depends_on:
      - medai-app
    restart: unless-stopped

volumes:
  redis_data:
